services:
  - type: web
    name: zalo-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    disk:
      name: zalo-data
      mountPath: /app/zalo_data
      sizeGB: 1
    staticPublishPath: ./views # Add this line