services:
  - type: web
    name: zalo-api
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: SESSION_SECRET
        generateValue: true
      - key: MESSAGE_WEBHOOK_URL
        sync: false
      - key: GROUP_EVENT_WEBHOOK_URL
        sync: false
      - key: REACTION_WEBHOOK_URL
        sync: false
    disk:
      name: zalo-data
      mountPath: /app/zalo_data
      sizeGB: 1
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
    routes:
      - type: rewrite
        source: /dashboard/*
        destination: /dashboard
      - type: rewrite
        source: /api/*
        destination: /api
      - type: rewrite
        source: /*
        destination: /index.html
    healthCheckPath: /health